version: "3.7"
services:
  database:
    image: mongo
    volumes: 
      - mongo-volume:/pa11ydata
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
  web:
    depends_on:
      - database
    image: derekz/pa11y-docker:latest
    # build: .
    ports:
      - "4000:4000"
    expose:
      - "4000"
    restart: always
volumes:
  mongo-volume:
